### ISSUE TITLE
GBA template image broken

### ISSUE THREAD

**Issue by izzergh** [quinton-ashley/bottlenose#6]
The transparent box art used as a placeholder was appearing as a broken image symbol. Checking the source [https://i.warosu.org/data/vr/img/0012/83/1387453429811.png](https://i.warosu.org/data/vr/img/0012/83/1387453429811.png) got me to the image after waiting a second to make sure I was human. Manually copying the image into the folder fixed the issue.

Suggested fix: include template images as assets with the releases and use those local files.

Let me know if my assessment is inaccurate!

**Comment by quinton-ashley** [comment]
Thank you for letting me know!  I decided to just edit that image and upload it to [bottlenose-img](https://github.com/quinton-ashley/bottlenose-img).  I don't include all the template images in the app because not all users will need all of them and it adds to the app size.  I'll let you know when I release this fix.

**Comment by quinton-ashley** [comment]
Fully fixed in v1.2.  You might have to delete the old gba placeholder image `emu/bottlenose/gba/_TEMPLATE/img`.  Do this before loading the new version of Bottlenose.  Sorry about that!  Thanks for catching it.
